### PR TITLE
Pass capture options for `setCameraEnabled` and `setMicrophone`

### PR DESCRIPTION
**Pull request by hiroshihorie**
I can add the default options to `ConnectOptions` but that will be only used when calling
`setCameraEnabled` `setMicrophoneEnabled` etc since creating track directly by `LocalAudioTrack.createTrack` has no access to the `Room.connectOptions`

https://linear.app/livekit/issue/LK-318/swift-support-default-capture-settings

### CODE REVIEW

**Comment by davidzhao** [comment]
> since creating track directly by `LocalAudioTrack.createTrack` has no access to the `Room.connectOptions`

I think the idea is that we could set defaults for the room that get honored. Would it be possible to access those options somehow?

**Comment by hiroshihorie** [comment]
@davidzhao I could change the timing of the actual `Engine.factory.audioTrack` being called until `LocalAudioTrack.start` is called.

**Comment by hiroshihorie** [comment]
I think `setCamera(enabled:)` can still have `options` even if there will be default options in `ConnectOptions`.
just like publish options if empty, will fall back to options in `ConnectOptions`.

**Comment by hiroshihorie** [comment]
options have been removed

**Comment by hiroshihorie** [comment]
Ok setXXXX API's params have been simplified, If user wants to pass param they should use `publishTrack`

**Review by davidzhao — APPROVED** [review]

**Pull request merged**
