### PR TITLE
`VideoCaptureInterceptor` for frame processing

### PR DESCRIPTION
**Pull request by hiroshihorie**
This is the example usage https://github.com/livekit/multiplatform-swiftui-example/commit/c003dc2621a4789172de734f7791379bd36aabd4

**Consideration**
- Current design assumes the frame processing will be quite fast, I haven't tested what will happen if processing is slow (developer obviously needs to be careful).

### CODE REVIEW

**Comment by davidzhao** [comment]
is it possible to chain them? i.e. in the future, would be flexible enough to do <interceptor 1> -> <interceptor 2>, etc.

Even for things such as end to end encryption, could be done via these kind of interceptors.

**Review by boks1971 — APPROVED** [review]
This is great. Like @davidzhao mentioned would be good to think about chaining at some point.

Generally thinking about media as a pipe and processors along the path would be great. Like the gstreamer design.

**Comment by hiroshihorie** [comment]
Ok boss(es) !!! Will check out gstreamer design

**Comment by boks1971** [comment]
hahaha I am just a pawn in the chess of life :-)

**Pull request merged**
